### ISSUE TITLE
Chapter 3 - Checklist

### ISSUE THREAD

**Issue by abrightman88** [cisagov/LME#70] opened 2023-11-23 12:27 UTC
Hi,

I'm upto Chapter 3 Checklist, however the kibana webpage doesn't load. I've tried on the Linux ELK server itself (https://127.0.0.1) and that doesn't load either (unable to connect)

I can't see port 443 as listening when running sudo ss -ltn 
I'm not sure what I'm missing. What troubleshooting can i do?

 

Thanks

**Comment by mitchelbaker-cisa** [comment] 2023-11-24 17:44
Hello, I would check the following to troubleshoot: 

1. When you run the command `sudo docker stack ps lme` do you see all three ELK services running on the Linux server? 
2. Are the [LME certificates](https://github.com/cisagov/LME/blob/main/docs/markdown/chapter3/chapter3.md#commands) imported on the computer you're using to try and access Kibana? 

When you run `ip addr` from the Linux server, the IP address after the indicator `inet` is the one you should be using to access Kibana. 127.0.0.1, or localhost, would not allow you to connect.

**Comment by mitchelbaker-cisa** [comment] 2023-11-27 19:04
> Hi,
> 
> Yes, I see all 3 running. There are "shutdown instances" displaying as well with the reason of "task non-zero exit" but there is one of each instance running.
> 
> Yes, the certificates have been imported to the machine which will be connecting.
> 
> I was trying localhost for testing purposes when it wasn't loading on the machine with the certificates installed. I am able to ping the elasticsearch server from that machine with the certificates but no luck with accessing it via the web interface
> 
> Thanks

Okay good, then in that case if each service has its state set to running seems the issue is the Linux IP you're using to access Kibana. Were you able to run `ip addr`, find the IP address next to `inet`, and use this one instead?

**Comment by abrightman88** [comment] 2023-11-28 09:00
Hi,

I've tried connecting to it via the ip address shown when running that command. I still receive the same "refused to connect" response. The ip address shown when running that command does ping from the machine I'm accessing it from. It also has the certifiate installed

Thanks

**Comment by mitchelbaker-cisa** [comment] 2023-11-28 17:37
> Hi,
> 
> I've tried connecting to it via the ip address shown when running that command. I still receive the same "refused to connect" response. The ip address shown when running that command does ping from the machine I'm accessing it from. It also has the certifiate installed
> 
> Thanks

Okay, in that case let's try your Linux server's IPv4 address for eth0 and see if that one works. Usually when you first login it should display this under system information.

**Comment by abrightman88** [comment] 2023-11-29 08:59
Hi,

It definitely has the ip address that I'm using to try and access it. It responds to ping from anotehr device on the network that I'm trying to access it from. eth0 is the same ip address as that one showing when i run the comand ip addr

I've ran the command sudo lsof -i -P -n | grep LISTEN to view which ports are listening and 443 is not listed

Thanks

**Comment by cbaxley** [comment] 2023-11-29 09:51
What is the output of this command? 
`sudo docker ps`
What we are looking for is how long the elasticsearch container has been up. 
Also, can you give the output of 
`sudo ls -l /opt/lme`
We are looking for the ownership of the `backups` folder. 
If it is owned by root, it can cause the elastic container not to start. 
The fix is 
`sudo chown -R 1000:1000 /opt/lme/backups`
Let us know if that helps the container to stay running.

**Comment by cbaxley** [comment] 2023-11-29 10:45
It was a bug in the 1.0 release. We just released a 1.1.0 version. After you get it running stable, maybe try moving to the next version.

**Comment by abrightman88** [comment] 2023-12-05 14:03
Hi,

All is settled and working as should. I've tried to upgrade but i dont have access to /opt/lme as the standard user and can't change directory as root. How would i browse to the directory to launch git pull?

Thanks

**Comment by aarz-snl** [comment] 2024-01-02 13:15
I would use "sudo chmod" and "sudo chown" as needed to give /opt/lme appropriate permissions to the user you wish to have access to it. This path is locked down due the sensitive data that exists in it after install. 

You could also do a "sudo su" and navigate to the path as needed. As noted you have to do one of these solutions because there is no "sudo cd"

**Comment by llwaterhouse** [comment] 2024-02-10 17:17
If you are still having issues, please respond by Feb. 17.  Otherwise we will be closing this issue.  Thank you.

**Closed** 2024-03-01 17:35 UTC
Labels: question, addressed
